---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-pipeline-dev
  namespace: dev-core
  labels:
    app: core-pipeline
    environment: dev
    app.kubernetes.io/name: core-pipeline
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-pipeline
      environment: dev
  template:
    metadata:
      labels:
        app: core-pipeline
        environment: dev
    spec:
      containers:
      - name: core-pipeline
        image: ghcr.io/uz0/core-pipeline:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3000"

        # PostgreSQL connection (CloudNativePG)
        - name: POSTGRES_HOST
          value: "infrastructure-postgres-rw.infrastructure.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "core_pipeline_dev"
        - name: POSTGRES_USER
          value: "core_dev_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-dev-credentials
              key: password

        # Kafka connection (Strimzi)
        - name: KAFKA_BROKERS
          value: "infrastructure-kafka-kafka-bootstrap.infrastructure.svc.cluster.local:9092"
        - name: KAFKA_CLIENT_ID
          value: "core-pipeline-dev"
        - name: KAFKA_GROUP_ID
          value: "core-pipeline-dev-group"

        # Redis connection (if using existing Redis)
        - name: REDIS_HOST
          value: "infrastructure-redis-master.infrastructure.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-dev-credentials
              key: password
              optional: true

        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: core-pipeline-dev
  namespace: dev-core
  labels:
    app: core-pipeline
    environment: dev
spec:
  selector:
    app: core-pipeline
    environment: dev
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-pipeline-dev
  namespace: dev-core
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: dev-core-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - core-pipeline.dev.theedgestory.org
      secretName: core-pipeline-dev-tls
  rules:
    - host: core-pipeline.dev.theedgestory.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core-pipeline-dev
                port:
                  number: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: dev-core
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-dev-credentials
  namespace: dev-core
type: Opaque
stringData:
  password: "REPLACE_WITH_ACTUAL_PASSWORD"  # TODO: Replace with real password

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-dev-credentials
  namespace: dev-core
  annotations:
    description: "Optional - only if using Redis"
type: Opaque
stringData:
  password: "REPLACE_WITH_ACTUAL_PASSWORD"  # TODO: Replace with real password
