---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-pipeline-prod
  namespace: prod-core
  labels:
    app: core-pipeline
    environment: prod
    app.kubernetes.io/name: core-pipeline
    app.kubernetes.io/instance: prod
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 2  # Production has 2 replicas for HA
  selector:
    matchLabels:
      app: core-pipeline
      environment: prod
  template:
    metadata:
      labels:
        app: core-pipeline
        environment: prod
    spec:
      containers:
      - name: core-pipeline
        image: ghcr.io/uz0/core-pipeline:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"

        # PostgreSQL connection (CloudNativePG)
        - name: POSTGRES_HOST
          value: "infrastructure-postgres-rw.infrastructure.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "core_pipeline_prod"
        - name: POSTGRES_USER
          value: "core_prod_user"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-prod-credentials
              key: password

        # Kafka connection (Strimzi)
        - name: KAFKA_BROKERS
          value: "infrastructure-kafka-kafka-bootstrap.infrastructure.svc.cluster.local:9092"
        - name: KAFKA_CLIENT_ID
          value: "core-pipeline-prod"
        - name: KAFKA_GROUP_ID
          value: "core-pipeline-prod-group"

        # Redis connection (if using existing Redis)
        - name: REDIS_HOST
          value: "infrastructure-redis-master.infrastructure.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-prod-credentials
              key: password
              optional: true

        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: core-pipeline-prod
  namespace: prod-core
  labels:
    app: core-pipeline
    environment: prod
spec:
  selector:
    app: core-pipeline
    environment: prod
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-pipeline-prod
  namespace: prod-core
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: prod-core-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - core-pipeline.theedgestory.org
      secretName: core-pipeline-prod-tls
  rules:
    - host: core-pipeline.theedgestory.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: core-pipeline-prod
                port:
                  number: 80

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: prod-core
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-prod-credentials
  namespace: prod-core
type: Opaque
stringData:
  password: "REPLACE_WITH_ACTUAL_PASSWORD"  # TODO: Replace with real password

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-prod-credentials
  namespace: prod-core
  annotations:
    description: "Optional - only if using Redis"
type: Opaque
stringData:
  password: "REPLACE_WITH_ACTUAL_PASSWORD"  # TODO: Replace with real password
