apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:uz0/core-charts.git'
    targetRevision: main
    path: charts/postgres
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
