apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-core-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:uz0/core-pipeline.git'
    targetRevision: main
    path: charts/core-pipeline
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
