---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: kubero
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: kubero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        volumeMounts:
        - name: data
          mountPath: /var/lib/registry
        - name: auth
          mountPath: /auth
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: registry-data
      - name: auth
        secret:
          secretName: registry-auth

---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: kubero
spec:
  selector:
    app: registry
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: kubero
type: Opaque
stringData:
  # htpasswd generated: kubero:kubero
  htpasswd: |
    kubero:$2y$05$czQZpvtDYc5OzM/1r1pH0eAplT/okohh/mXoWl/Y65ZP/8/jnSWZq
