---
# Enhanced Kubero ConfigMap with external links
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubero-config
  namespace: kubero
data:
  config.yaml: |
    buildpacks:
    - build:
        repository: heroku/builder
        tag: "22"
      fetch:
        repository: ghcr.io/kubero-dev/buildpacks/fetch
        tag: v1.2
      name: heroku
      run:
        repository: heroku/heroku
        tag: "22"
    - build:
        repository: paketobuildpacks/builder
        tag: base
      fetch:
        repository: ghcr.io/kubero-dev/buildpacks/fetch
        tag: v1.2
      name: paketo
      run:
        repository: paketobuildpacks/run
        tag: base-cnb
    clusterIssuer: ""
    clusterissuer: letsencrypt-prod
    kubero:
      admin:
        disabled: false
      banner:
        bgColor: '#8560A9'
        bgcolor: '#8560A9'
        fontcolor: azure
        message: '🌟 The Edge Story Services: <a href="https://grafana.theedgestory.org" target="_blank" style="color:#4ade80">📊 Grafana</a> | <a href="https://s3-admin.theedgestory.org" target="_blank" style="color:#4ade80">💾 MinIO</a> | <a href="https://kafka.theedgestory.org" target="_blank" style="color:#4ade80">📨 Kafka</a> | <a href="https://status.theedgestory.org" target="_blank" style="color:#4ade80">📈 Status</a>'
        show: true
      console:
        enabled: true
      readonly: false
    # Prometheus configuration for metrics
    prometheus:
      enabled: true
      url: http://prometheus.monitoring.svc.cluster.local:9090
    notifications: []
    podSizeList:
    - default: true
      description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
      name: small
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 0.5Gi
    - description: 'Medium (CPU: 1, Memory: 2Gi)'
      name: medium
      resources:
        limits:
          cpu: 2000m
          memory: 4Gi
        requests:
          cpu: 1000m
          memory: 2Gi
    - description: 'Large (CPU: 2, Memory: 4Gi)'
      name: large
      resources:
        limits:
          cpu: 2000m
          memory: 4Gi
        requests:
          cpu: 2000m
          memory: 4Gi
    templates:
      catalogs:
      - description: Kubero templates
        index:
          format: json
          url: https://raw.githubusercontent.com/kubero-dev/templates/main/index.json
        name: Kubero
        templateBasePath: https://raw.githubusercontent.com/kubero-dev/kubero/main/services/
      - description: Kubero templates
        index:
          format: json
          url: https://raw.githubusercontent.com/kubero-dev/templates/main/index-frameworks.json
        name: Kubero Frameworks
        templateBasePath: https://raw.githubusercontent.com/kubero-dev/kubero/main/services/
      enabled: true

---
# Kubero environment variables for Prometheus integration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubero
  namespace: kubero
spec:
  template:
    spec:
      containers:
      - name: kubero
        env:
        - name: KUBERO_PROMETHEUS_ENABLED
          value: "true"
        - name: KUBERO_PROMETHEUS_ENDPOINT
          value: "http://prometheus.monitoring.svc.cluster.local:9090"
