---
# Kubero OAuth Configuration for Google Authentication
# Kubero supports OAuth2 authentication through environment variables

apiVersion: v1
kind: ConfigMap
metadata:
  name: kubero-oauth-config
  namespace: kubero
data:
  # OAuth Configuration
  KUBERO_AUTH_ENABLED: "true"
  KUBERO_AUTH_TYPE: "oauth2"
  KUBERO_AUTH_GITHUB_ENABLED: "false"
  KUBERO_AUTH_GOOGLE_ENABLED: "true"
  KUBERO_AUTH_GOOGLE_SCOPE: "openid email profile"
  KUBERO_AUTH_GOOGLE_CALLBACK_URL: "https://dev.theedgestory.org/auth/google/callback"
  KUBERO_SESSION_KEY: "kubero-session-key-change-in-production"

---
# Patch Kubero deployment to add OAuth environment variables
# kubectl apply -f kubero-oauth.yaml
# kubectl patch deployment kubero -n kubero --patch-file kubero-oauth-patch.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubero
  namespace: kubero
spec:
  template:
    spec:
      containers:
      - name: kubero
        env:
        # Existing env vars...
        - name: KUBERO_PROMETHEUS_ENABLED
          value: "true"
        - name: KUBERO_PROMETHEUS_ENDPOINT
          value: "http://prometheus.monitoring.svc.cluster.local:9090"
        # OAuth Configuration
        - name: KUBERO_AUTH_ENABLED
          value: "true"
        - name: KUBERO_AUTH_TYPE
          value: "oauth2"
        - name: KUBERO_AUTH_GITHUB_ENABLED
          value: "false"
        - name: KUBERO_AUTH_GOOGLE_ENABLED
          value: "true"
        - name: KUBERO_AUTH_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-oauth
              key: client-id
              optional: true
        - name: KUBERO_AUTH_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-oauth
              key: client-secret
              optional: true
        - name: KUBERO_AUTH_GOOGLE_SCOPE
          value: "openid email profile"
        - name: KUBERO_AUTH_GOOGLE_CALLBACK_URL
          value: "https://dev.theedgestory.org/auth/google/callback"
        - name: KUBERO_SESSION_KEY
          value: "kubero-production-session-key-2024"
        - name: KUBERO_WEBHOOK_URL
          value: "https://dev.theedgestory.org"
