apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"cert-manager","namespace":"argocd"},"spec":{"destination":{"namespace":"cert-manager","server":"https://kubernetes.default.svc"},"project":"default","source":{"chart":"cert-manager","helm":{"values":"installCRDs: true\n"},"repoURL":"https://charts.jetstack.io","targetRevision":"v1.13.0"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
    link.argocd.argoproj.io/external-link: https://cert-manager.io/docs/
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
