apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    link.argocd.argoproj.io/external-link: https://core-pipeline.dev.theedgestory.org
    argocd.argoproj.io/sync-wave: "2"
  name: core-pipeline-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev-core
    server: https://kubernetes.default.svc
  project: applications
  source:
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
        - dev.tag.yaml
    path: charts/core-pipeline
    repoURL: https://github.com/uz0/core-charts
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
