apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-pipeline-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/uz0/core-charts.git
    targetRevision: HEAD
    path: charts/core-pipeline
    helm:
      valueFiles:
        - values-prod.yaml
        - prod.tag.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
