apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"link.argocd.argoproj.io/external-link":"https://grafana.dev.theedgestory.org"},"name":"grafana","namespace":"argocd"},"spec":{"destination":{"namespace":"monitoring","server":"https://kubernetes.default.svc"},"project":"monitoring","source":{"chart":"grafana","repoURL":"https://grafana.github.io/helm-charts","targetRevision":"7.0.0"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true}}}}
    link.argocd.argoproj.io/external-link: https://grafana.dev.theedgestory.org
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 7.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
