apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/uz0/core-charts.git
    targetRevision: main
    path: charts/infrastructure/kafka-ui
    helm:
      values: |
        replicaCount: 1
        image:
          repository: provectuslabs/kafka-ui
          tag: latest
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: kafka.dev.theedgestory.org
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
