apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/uz0/core-charts.git
    targetRevision: main
    path: charts/infrastructure/kafka
    helm:
      values: |
        kafka:
          image:
            registry: docker.io
            repository: bitnamilegacy/kafka
            tag: 3.8.0-debian-12-r3
          kraft:
            enabled: true
          zookeeper:
            enabled: false
          controller:
            replicaCount: 1
          broker:
            replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-infra
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
