apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.17.3
    chart: tempo-distributed
    helm:
      values: |
        ingester:
          replicas: 3
        distributor:
          replicas: 1
        querier:
          replicas: 1
        queryFrontend:
          replicas: 1
        compactor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
