---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: monitoring
data:
  config.yml: |
    kafka:
      clusters:
        - name: main-cluster
          bootstrapServers: kafka.infrastructure.svc.cluster.local:9092
    auth:
      type: OAUTH2
      oauth2:
        client:
          cognito:
            clientId: ${OAUTH_CLIENT_ID}
            clientSecret: ${OAUTH_CLIENT_SECRET}
            scope: openid,profile,email
            user-name-attribute: email
            provider-url: https://accounts.google.com
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            issuer-uri: https://accounts.google.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "main-cluster"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "kafka.infrastructure.svc.cluster.local:9092"
        - name: AUTH_TYPE
          value: "OAUTH2"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-oauth
              key: client-id
              optional: true
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-oauth
              key: client-secret
              optional: true
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE
          value: "openid,profile,email"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI
          value: "https://kafka.theedgestory.org/login/oauth2/code/google"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_ISSUER_URI
          value: "https://accounts.google.com"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_AUTHORIZATION_URI
          value: "https://accounts.google.com/o/oauth2/v2/auth"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_TOKEN_URI
          value: "https://oauth2.googleapis.com/token"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_INFO_URI
          value: "https://openidconnect.googleapis.com/v1/userinfo"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_JWK_SET_URI
          value: "https://www.googleapis.com/oauth2/v3/certs"
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_NAME_ATTRIBUTE
          value: "email"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: monitoring
spec:
  selector:
    app: kafka-ui
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui
  namespace: monitoring
spec:
  ingressClassName: traefik
  rules:
  - host: kafka.theedgestory.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafka-ui
            port:
              number: 8080
