apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-csrf-config
  namespace: authentik
data:
  AUTHENTIK_CSRF_TRUSTED_ORIGINS: "https://auth.theedgestory.org"
  DJANGO_CSRF_TRUSTED_ORIGINS: "https://auth.theedgestory.org"
  AUTHENTIK_CSRF_COOKIE_NAME: "authentik_csrf"
  AUTHENTIK_CSRF_HEADER_NAME: "X-Authentik-CSRF"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-server
  namespace: authentik
spec:
  template:
    spec:
      containers:
      - name: authentik
        envFrom:
        - configMapRef:
            name: authentik-csrf-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
  namespace: authentik
spec:
  template:
    spec:
      containers:
      - name: authentik
        envFrom:
        - configMapRef:
            name: authentik-csrf-config