---
# Gatus Status Page Deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: monitoring
data:
  config.yaml: |
    web:
      port: 8080

    endpoints:
      - name: Authentik
        group: Identity
        url: https://auth.theedgestory.org
        interval: 60s
        conditions:
          - "[STATUS] == 200 || [STATUS] == 302"
          - "[RESPONSE_TIME] < 5000"

      - name: ArgoCD
        group: Platform
        url: https://argo.theedgestory.org
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 5000"

      - name: Grafana
        group: Monitoring
        url: https://grafana.theedgestory.org
        interval: 60s
        conditions:
          - "[STATUS] == 200 || [STATUS] == 302"
          - "[RESPONSE_TIME] < 5000"

      - name: Kafka UI
        group: Infrastructure
        url: https://kafka.theedgestory.org
        interval: 60s
        conditions:
          - "[STATUS] == 200 || [STATUS] == 302"
          - "[RESPONSE_TIME] < 5000"

      - name: MinIO Console
        group: Storage
        url: https://s3-admin.theedgestory.org
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 5000"

      - name: Core Pipeline Dev
        group: Applications
        url: https://core-pipeline.dev.theedgestory.org/api-docs
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 5000"

      - name: Core Pipeline Prod
        group: Applications
        url: https://core-pipeline.theedgestory.org/api-docs
        interval: 60s
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 5000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
      - name: gatus
        image: twinproduction/gatus:v5.7.0
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: gatus-config

---
apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: monitoring
spec:
  selector:
    app: gatus
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: status.theedgestory.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gatus
                port:
                  number: 80
  tls:
    - hosts:
        - status.theedgestory.org
      secretName: cloudflare-origin-tls