#!/bin/bash

# Fix redirect loops by switching from Cloudflare Proxy to Cloudflare Tunnel
# The tunnel is already configured and running, we just need to update DNS

echo "========================================="
echo "Fixing Redirect Loops via Cloudflare Tunnel"
echo "========================================="
echo ""
echo "The Cloudflare Tunnel is already configured and running."
echo "We need to update DNS records to use the tunnel instead of the proxy."
echo ""

TUNNEL_ID="6c01bbbf-3488-4182-b17b-3ac004a02d99"

echo "Step 1: Check tunnel status"
echo "============================"
kubectl get pods -n infrastructure | grep cloudflared
echo ""

echo "Step 2: Update Cloudflare DNS Records"
echo "======================================"
echo ""
echo "You have two options:"
echo ""
echo "OPTION A: Use Cloudflare CLI (if you have API token)"
echo "------------------------------------------------------"
echo "Install cloudflared CLI and run:"
echo ""
echo "# First, verify the tunnel is registered:"
echo "cloudflared tunnel info $TUNNEL_ID"
echo ""
echo "# Then update DNS records to use the tunnel:"
echo "cloudflared tunnel route dns $TUNNEL_ID auth.theedgestory.org"
echo "cloudflared tunnel route dns $TUNNEL_ID argo.theedgestory.org"
echo "cloudflared tunnel route dns $TUNNEL_ID kafka.theedgestory.org"
echo ""
echo "OPTION B: Update via Cloudflare Dashboard (Manual)"
echo "---------------------------------------------------"
echo "1. Login to https://dash.cloudflare.com"
echo "2. Select 'theedgestory.org' domain"
echo "3. Go to DNS → Records"
echo "4. Delete or modify these A/CNAME records:"
echo "   - auth.theedgestory.org"
echo "   - argo.theedgestory.org"
echo "   - kafka.theedgestory.org"
echo ""
echo "5. Add new CNAME records pointing to the tunnel:"
echo "   Name: auth"
echo "   Target: $TUNNEL_ID.cfargotunnel.com"
echo "   Proxy: Enabled (orange cloud)"
echo ""
echo "   Name: argo"
echo "   Target: $TUNNEL_ID.cfargotunnel.com"
echo "   Proxy: Enabled (orange cloud)"
echo ""
echo "   Name: kafka"
echo "   Target: $TUNNEL_ID.cfargotunnel.com"
echo "   Proxy: Enabled (orange cloud)"
echo ""

echo "Step 3: Verify Tunnel Configuration"
echo "===================================="
echo "The tunnel is already configured to route these domains:"
echo ""
kubectl get configmap cloudflared-config -n infrastructure -o yaml | grep -E "hostname:|service:" | head -20
echo ""

echo "Step 4: Test After DNS Update"
echo "=============================="
echo "After updating DNS (wait 1-2 minutes for propagation):"
echo ""
echo "curl -I https://auth.theedgestory.org"
echo "curl -I https://argo.theedgestory.org"
echo "curl -I https://kafka.theedgestory.org"
echo ""
echo "You should get HTTP 200 or 302 responses, NOT 308 redirects."
echo ""

echo "Alternative: Test Immediately (bypass DNS)"
echo "=========================================="
echo "While waiting for DNS propagation, you can test by adding to /etc/hosts:"
echo ""
echo "# Get the Cloudflare Tunnel IP (usually Cloudflare's anycast IP)"
echo "104.21.0.0 auth.theedgestory.org"
echo "104.21.0.0 argo.theedgestory.org"
echo "104.21.0.0 kafka.theedgestory.org"
echo ""
echo "Note: The tunnel automatically handles SSL/TLS termination."
echo ""

echo "Current Tunnel Status:"
echo "======================"
kubectl logs -n infrastructure deployment/cloudflared --tail=10