apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.21
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 22
              name: ssh
          env:
            - name: GITEA__server__ROOT_URL
              value: "http://gitea.argocd.svc.cluster.local:3000"
            - name: GITEA__server__DOMAIN
              value: "gitea.argocd.svc.cluster.local"
            - name: GITEA__server__HTTP_PORT
              value: "3000"
            - name: GITEA__server__DISABLE_SSH
              value: "false"
            - name: GITEA__server__START_SSH_SERVER
              value: "true"
            - name: GITEA__server__SSH_PORT
              value: "22"
            - name: GITEA__database__DB_TYPE
              value: "sqlite3"
            - name: GITEA__security__INSTALL_LOCK
              value: "true"
            - name: GITEA__service__DISABLE_REGISTRATION
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-data
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: argocd
spec:
  selector:
    app: gitea
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: ssh
      port: 22
      targetPort: 22
  type: ClusterIP
