apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-init-script
  namespace: argocd
data:
  init.sh: |
    #!/bin/sh
    set -e
    
    echo "=== Initializing Gitea for ArgoCD ==="
    
    # Wait for Gitea API to be ready
    echo "Waiting for Gitea API..."
    i=1
    while [ $i -le 60 ]; do
      if wget -q --spider http://gitea.argocd.svc.cluster.local:3000 2>/dev/null; then
        echo "✅ Gitea is ready"
        break
      fi
      echo "Waiting... ($i/60)"
      i=$((i + 1))
      sleep 5
    done
    
    # Clone from GitHub
    echo "Cloning from GitHub..."
    cd /tmp
    git clone --depth 1 https://github.com/uz0/core-charts.git
    cd core-charts
    
    # Create user and repository via API (skip if exists)
    echo "Creating Gitea user and repository..."
    
    # Create admin user
    wget --post-data='{"username":"argocd","password":"argocd-password","email":"argocd@local","must_change_password":false,"send_notify":false}' \
      --header='Content-Type: application/json' \
      -O- \
      http://gitea.argocd.svc.cluster.local:3000/api/v1/admin/users 2>&1 || echo "User may already exist"
    
    # Create repository using basic auth
    wget --post-data='{"name":"core-charts","private":false,"auto_init":false}' \
      --header='Content-Type: application/json' \
      --http-user=argocd \
      --http-password=argocd-password \
      -O- \
      http://gitea.argocd.svc.cluster.local:3000/api/v1/user/repos 2>&1 || echo "Repository may already exist"
    
    # Push to Gitea
    echo "Pushing to Gitea..."
    git remote add gitea http://argocd:argocd-password@gitea.argocd.svc.cluster.local:3000/argocd/core-charts.git
    git push gitea main --force
    
    echo "✅ Gitea initialization complete"
    echo "Repository URL: http://gitea.argocd.svc.cluster.local:3000/argocd/core-charts.git"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-init
  namespace: argocd
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: git-init
          image: alpine/git:latest
          command: ["/bin/sh", "/scripts/init.sh"]
          volumeMounts:
            - name: init-script
              mountPath: /scripts
          env:
            - name: GIT_SSL_NO_VERIFY
              value: "true"
      volumes:
        - name: init-script
          configMap:
            name: gitea-init-script
            defaultMode: 0755
