#!/bin/bash

# Script to configure Authentik with Google OAuth and LDAP after Cloudflare redirect issue is fixed

echo "========================================="
echo "Authentik SSO Configuration Script"
echo "========================================="
echo ""
echo "Prerequisites:"
echo "1. Cloudflare redirect loops must be fixed"
echo "2. You must be able to access https://auth.theedgestory.org"
echo "3. You need Google OAuth credentials (client ID and secret)"
echo ""
echo "Press Enter to continue or Ctrl+C to cancel..."
read

# Check if services are accessible
echo "Checking service availability..."
if curl -I https://auth.theedgestory.org 2>/dev/null | grep -q "308"; then
    echo "❌ ERROR: Redirect loop still present!"
    echo "Please fix Cloudflare settings first. See CLOUDFLARE-FIX-REQUIRED.md"
    exit 1
fi

echo "✅ Services appear to be accessible"
echo ""

echo "Initial Admin Credentials:"
echo "=========================="
echo "URL: https://auth.theedgestory.org"
echo "Email: dcversus@gmail.com"
echo "Password: authentik-admin-password-2024"
echo ""
echo "After logging in, follow these steps:"
echo ""

echo "Step 1: Configure Google OAuth Provider"
echo "========================================"
echo "1. Navigate to Admin Interface → Providers"
echo "2. Click 'Create' → 'OAuth2/OpenID Provider'"
echo "3. Configure:"
echo "   - Name: google-oauth"
echo "   - Client ID: [Your Google OAuth Client ID]"
echo "   - Client Secret: [Your Google OAuth Client Secret]"
echo "   - Redirect URIs: https://auth.theedgestory.org/source/oauth/callback/google/"
echo ""

echo "Step 2: Create Google OAuth Source"
echo "==================================="
echo "1. Navigate to Admin Interface → Sources"
echo "2. Click 'Create' → 'Google OAuth Source'"
echo "3. Configure:"
echo "   - Name: Google"
echo "   - Slug: google"
echo "   - Consumer Key: [Your Google OAuth Client ID]"
echo "   - Consumer Secret: [Your Google OAuth Client Secret]"
echo "   - Allowed domains: gmail.com"
echo ""

echo "Step 3: Configure LDAP Outpost"
echo "==============================="
echo "1. Navigate to Admin Interface → Outposts"
echo "2. Click 'Create' → 'LDAP Outpost'"
echo "3. Configure:"
echo "   - Name: ldap-outpost"
echo "   - Type: LDAP"
echo "   - Bind DN: cn=admin,dc=theedgestory,dc=org"
echo "   - Search base: dc=theedgestory,dc=org"
echo ""

echo "Step 4: Create Service Accounts"
echo "================================"
echo "Services that will use LDAP:"
echo ""
echo "ArgoCD LDAP Configuration:"
echo "  Host: authentik-ldap-outpost.authentik.svc.cluster.local"
echo "  Port: 636"
echo "  Base DN: dc=theedgestory,dc=org"
echo "  Bind DN: cn=argocd,ou=services,dc=theedgestory,dc=org"
echo ""
echo "Grafana LDAP Configuration:"
echo "  Host: authentik-ldap-outpost.authentik.svc.cluster.local"
echo "  Port: 636"
echo "  Base DN: dc=theedgestory,dc=org"
echo "  Bind DN: cn=grafana,ou=services,dc=theedgestory,dc=org"
echo ""
echo "MinIO LDAP Configuration:"
echo "  Server: ldaps://authentik-ldap-outpost.authentik.svc.cluster.local:636"
echo "  Base DN: dc=theedgestory,dc=org"
echo "  Bind DN: cn=minio,ou=services,dc=theedgestory,dc=org"
echo ""

echo "Step 5: Update Service Configurations"
echo "======================================"
echo "Run these commands to update each service:"
echo ""
echo "# ArgoCD"
echo "kubectl edit configmap argocd-cm -n argocd"
echo "# Add LDAP configuration under data:"
echo ""
echo "# Grafana"
echo "kubectl edit configmap grafana-config -n monitoring"
echo "# Update LDAP settings"
echo ""
echo "# MinIO"
echo "kubectl edit deployment minio -n infrastructure"
echo "# Add LDAP environment variables"
echo ""

echo "Step 6: Restrict to dcversus@gmail.com"
echo "======================================="
echo "1. In Authentik, create a policy:"
echo "   - Type: Expression Policy"
echo "   - Name: only-dcversus"
echo "   - Expression: return request.user.email == 'dcversus@gmail.com'"
echo "2. Apply this policy to all applications"
echo ""

echo "Verification Commands:"
echo "====================="
echo "# Test LDAP connection"
echo "ldapsearch -x -H ldaps://authentik-ldap-outpost.authentik.svc.cluster.local:636 -D 'cn=admin,dc=theedgestory,dc=org' -W -b 'dc=theedgestory,dc=org'"
echo ""
echo "# Check Authentik logs"
echo "kubectl logs -n authentik deployment/authentik-server -f"
echo ""

echo "========================================="
echo "Configuration script complete!"
echo "Please follow the steps above in the Authentik UI"
echo "========================================="